### ISSUE TITLE
Report on a namspace_err

### ISSUE THREAD

**Issue by sabracrolleton** [tshatrov/webgunk#1]
Hello,

I tried parsing http://spec.commonmark.org/0.24/index.html with parse-url and it threw the error listed below. Your thoughts would be appreciated.

Sabra

NAMESPACE_ERR (14):
invalid uri for prefix `xmlns'
   [Condition of type RUNE-DOM::DOM-EXCEPTION]

Restarts:
 0: [*ABORT] Return to SLIME's top level.
 1: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {1007CC2423}>)

Backtrace:
  0: (RUNE-DOM::DOM-ERROR :NAMESPACE_ERR "invalid uri for prefix `xmlns'")
      Locals:
        ARGS = NIL
        FMT = "invalid uri for prefix`xmlns'"
        KEY = :NAMESPACE_ERR
  1: (RUNE-DOM::SAFE-SPLIT-QNAME "xmlns:dct" "")
      Locals:
        SB-DEBUG::ARG-0 = "xmlns:dct"
        SB-DEBUG::ARG-1 = ""
  2: ((:METHOD DOM:CREATE-ATTRIBUTE-NS (RUNE-DOM::DOCUMENT T T)) #<RUNE-DOM::DOCUMENT {1009811873}> #<unavailable argument> #<unavailable argument>) [fast-method]
      Locals:
        SB-DEBUG::ARG-2 = #<RUNE-DOM::DOCUMENT {1009811873}>
  3: ((:METHOD SAX:START-ELEMENT (RUNE-DOM::DOM-BUILDER T T T T)) #<RUNE-DOM::DOM-BUILDER {1007D1C0E3}> "http://www.w3.org/1999/xhtml" "span" #<unavailable argument> (#<HAX:STANDARD-ATTRIBUTE {1009816E53}>..
      Locals:
        SB-DEBUG::ARG-2 = #<RUNE-DOM::DOM-BUILDER {1007D1C0E3}>
        SB-DEBUG::ARG-3 = "http://www.w3.org/1999/xhtml"
        SB-DEBUG::ARG-4 = "span"
        SB-DEBUG::ARG-6 = (#<HAX:STANDARD-ATTRIBUTE {1009816E53}> #<HAX:STANDARD-ATTRIBUTE {1009816EB3}> #<HAX:STANDARD-ATTRIBUTE {1009816F13}> #<HAX:STANDARD-ATTRIBUTE {1009816F73}>)
  4: ((LABELS CLOSURE-HTML::RECURSE :IN CLOSURE-HTML:SERIALIZE-PT) #<SGML:PT SPAN ..>)
      Locals:
        SB-DEBUG::ARG-0 = #<SGML:PT SPAN ..>
  5: ((LABELS CLOSURE-HTML::RECURSE :IN CLOSURE-HTML:SERIALIZE-PT) #<SGML:PT SPAN ..>)
      Locals:
        SB-DEBUG::ARG-0 = #<SGML:PT SPAN ..>

**Comment by tshatrov** [comment]
The error happens within the html-parsing code, which is delegated to CXML-DOM library.

It appears that the page in question is misusing XML namespaces, which causes CXML to barf trying to parse it. In particular this snippet is causing the error:

```
<span xmlns:dct="http://purl.org/dc/terms/"
   href="http://purl.org/dc/dcmitype/Text" property="dct:title"
   rel="dct:type">CommonMark Spec</span>
```

This defines prefix "dct", however the element itself is not using this prefix. 

The following snippet does parse correctly:

```
<dct:span xmlns:dct="http://purl.org/dc/terms/"
   href="http://purl.org/dc/dcmitype/Text" property="dct:title"
   rel="dct:type">CommonMark Spec</span>
```

## Workaround

Fortunately there's a way to turn this all this namespace processing stuff off. You just need to bind dynamic variable `sax:*namespace-processing*` to nil. This works:

```
(let ((sax:*namespace-processing* nil))
   (parse-url "http://spec.commonmark.org/0.24/index.html"))
```

Maybe I should set this variable to nil by default. Usually namespaces aren't very important for web-scraping.

**Comment by sabracrolleton** [comment]
Thank you. I find it simultaneously amusing and disappointing that a page
dedicated to being the markdown spec misuses namespaces.

Sabra
